<Project Sdk="Microsoft.NET.Sdk">

	<!-- General Package Properties -->
	<PropertyGroup>
		<PackageId>BionicBoostersPlus</PackageId>
		<Version>1.0.0</Version>
		<Authors>Sgt_Imalas</Authors>
		<Copyright>$(AssemblyCopyright)</Copyright>
		<RepositoryUrl>https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods</RepositoryUrl>
	</PropertyGroup>

	<!-- Build Properties -->
	<PropertyGroup>
		<Configurations>Debug;Release</Configurations>
		<AssemblyName>BionicBoostersPlus</AssemblyName>
		<RootNamespace>BionicBoostersPlus</RootNamespace>
		<IsMod>true</IsMod>
		<GenerateMetadata>true</GenerateMetadata>
		<IsPacked>true</IsPacked>
	</PropertyGroup>


	<!-- Mod Info -->
	<PropertyGroup>
		<ModName>Bionics Expanded</ModName>
		<ModDescription>a ton of new boosters and skills to elevate your bionic duplicants to the next level</ModDescription>
		<MinimumSupportedBuild>$(TargetGameVersion)</MinimumSupportedBuild>
		<APIVersion>2</APIVersion>
	</PropertyGroup>


	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutDir>bin</OutDir>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\UtilLibs\UtilLibs.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Content\Defs\Items\" />
	</ItemGroup>
</Project>