<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<DoNotBuildAsMod>true</DoNotBuildAsMod>
		<TargetFramework>netstandard2.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
	  <None Include="ValidatePOFiles.cs" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Karambolo.PO.Minimal" Version="*" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Build.Framework" Version="*" />
		<PackageReference Include="Microsoft.Build.Utilities.Core" Version="*" />
	</ItemGroup>

	<ItemGroup>
		<Reference Remove="Assembly-CSharp" />
		<Reference Remove="Assembly-CSharp-firstpass" />
		<Reference Remove="0Harmony" />
		<Reference Remove="com.rlabrecque.steamworks.net" />
		<Reference Remove="FMODUnity" />
		<Reference Remove="UnityEngine" />
		<Reference Remove="UnityEngine.AssetBundleModule" />
		<Reference Remove="Unity.TextMeshPro" />
		<Reference Remove="UnityEngine.CoreModule" />
		<Reference Remove="UnityEngine.ImageConversionModule" />
		<Reference Remove="UnityEngine.ParticleSystemModule" />
		<Reference Remove="UnityEngine.Physics2DModule" />
		<Reference Remove="UnityEngine.PhysicsModule" />
		<Reference Remove="UnityEngine.UI" />
		<Reference Remove="UnityEngine.UIModule" />
		<Reference Remove="UnityEngine.TextRenderingModule" />
		<Reference Remove="Newtonsoft.Json" />
		<Reference Remove="netstandard" />
		<Reference Remove="UnityEngine.WebRequestModule" />
	</ItemGroup>
</Project>
