<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<DoNotBuildAsMod>true</DoNotBuildAsMod>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Magick.NET.Core" Version="14.16.0" />
		<PackageReference Include="Magick.NET-Q16-x64" Version="14.16.0" />
	</ItemGroup>
	<ItemGroup>
		<None Update="texconv.exe">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<PropertyGroup>
		<PlatformTarget>x64</PlatformTarget>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	</PropertyGroup>

	<ItemGroup>
		<Reference Remove="Assembly-CSharp" />
		<Reference Remove="Assembly-CSharp-firstpass" />
		<Reference Remove="0Harmony" />
		<Reference Remove="com.rlabrecque.steamworks.net" />
		<Reference Remove="FMODUnity" />
		<Reference Remove="UnityEngine" />
		<Reference Remove="UnityEngine.AssetBundleModule" />
		<Reference Remove="Unity.TextMeshPro" />
		<Reference Remove="UnityEngine.CoreModule" />
		<Reference Remove="UnityEngine.ImageConversionModule" />
		<Reference Remove="UnityEngine.ParticleSystemModule" />
		<Reference Remove="UnityEngine.Physics2DModule" />
		<Reference Remove="UnityEngine.PhysicsModule" />
		<Reference Remove="UnityEngine.UI" />
		<Reference Remove="UnityEngine.UIModule" />
		<Reference Remove="UnityEngine.TextRenderingModule" />
		<Reference Remove="Newtonsoft.Json" />
		<Reference Remove="netstandard" />
		<Reference Remove="UnityEngine.WebRequestModule" />
	</ItemGroup>
</Project>
