<Project Sdk="Microsoft.NET.Sdk">

	<!-- General Package Properties -->
	<PropertyGroup>
		<PackageId>BlueprintsV2</PackageId>
		<Version>6.2.0</Version>
		<Authors>Sgt_Imalas</Authors>
		<Copyright>$(AssemblyCopyright)</Copyright>
		<RepositoryUrl>https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods</RepositoryUrl>
	</PropertyGroup>

	<!-- Build Properties -->
	<PropertyGroup>
		
		<Configurations>Debug;Release</Configurations>
		<AssemblyName>BlueprintsV2</AssemblyName>
		<RootNamespace>BlueprintsV2</RootNamespace>
		<IsMod>true</IsMod>
		<SteamId>3468585385</SteamId>
		<GenerateMetadata>true</GenerateMetadata>
		<IsPacked>true</IsPacked>
	</PropertyGroup>


	<!-- Mod Info -->
	<PropertyGroup>
		<ModName>Blueprints Expanded</ModName>
		<ModDescription>Design and store your favourite designs, including building settings</ModDescription>
		<MinimumSupportedBuild>$(TargetGameVersion)</MinimumSupportedBuild>
		<APIVersion>2</APIVersion>
	</PropertyGroup>


	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutDir>bin</OutDir>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\UtilLibs\UtilLibs.csproj" />
	</ItemGroup>
	
	
  <ItemGroup>
    <Folder Include="BlueprintsV2\BlueprintData\DataTransfer\" />
    <Folder Include="BlueprintsV2\Visualizers\ReplacementVisualizers\Entities\" />
  </ItemGroup>
	
	<ItemGroup>
		<Reference Include="ONI_Together_API">
			<HintPath>..\TwitchLib\ONI_Together_API.dll</HintPath>
			<!--<HintPath>C:\Users\Admin\source\repos\Oxygen_Not_Included_Multiplayer\ONI_Together_API\bin\Debug\net472\ONI_Together_API.dll</HintPath>-->
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
			<HintPath>$(GameLibsFolder)\UnityEngine.InputLegacyModule.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>
</Project>
