
/// <summary>
/// The following type is an example on how to easily add additional data to blueprints for your modded buildings:
/// if you implement two static Methods "Blueprints_SetData" and "Blueprints_GetData" with the same parameters as shown here, the blueprints will automatically store and apply them
/// Optionally, you can implement "Blueprints_ID" to put the data under a specific key, otherwise it will use {AssemblyName_TypeName} as data key
/// </summary>
class IntegrationExample : KMonoBehaviour
{
	internal void SetData(string key1, string key2)
	{
		this.key1 = key1;
		this.key2 = key2;
	}
	string key1 = "", key2 = "";

	/// <summary>
	/// This static method will allow you to apply any additional data stored previously in Blueprints_GetData.
	/// </summary>
	/// <param name="source">The Gameobject of the newly constructed building</param>
	/// <param name="data">the additional data stored in the object that was generated by Blueprints_GetData</param>
	public static void Blueprints_SetData(GameObject source, JObject data)
	{
		if (source.TryGetComponent<IntegrationExample>(out var behavior))
		{
			var t1 = data.GetValue("Key1");
			if (t1 == null)
				return;
			var Key1 = t1.Value<string>(); //"Value1"

			var t2 = data.GetValue("Key2");
			if (t2 == null)
				return;
			var Key2 = t1.Value<string>(); //"Value2"
			behavior.SetData(Key1, Key2);

		}
	}
	/// <summary>
	/// This static method takes in the source gameobject and returns a JObject with all the additional data you give it. this data is then stored in the blueprint
	/// </summary>
	/// <param name="source">the gameobject the blueprint is made from</param>
	/// <returns>JObject of all the data to be stored in the blueprint</returns>
	public static JObject Blueprints_GetData(GameObject source)
	{
		if (source.TryGetComponent<IntegrationExample>(out var behavior))
		{
			return new JObject()
				{
					{ "Key1", behavior.key1},
					{ "Key2", behavior.key2},
				};
		}
		return null;
	}
	/// <summary>
	/// Optional Method!
	/// Allows you to register data under a specific key
	/// if omitted, the key will be AssemblyName_Typename of the class these methods sit in
	/// </summary>
	/// <returns>custom data key under which your data will be stored in the blueprint</returns>
	public static string Blueprints_ID()
	{
		return "Blueprints_ExampleDataKey";
	}
	/// <summary>
	/// Optional Method!
	/// Allows you to register data with a specific priority
	/// If multiple registrations for the same key exist,
	/// the registration with the hightest priority value will take effect
	/// if omitted, defaults to 0
	/// </summary>
	/// <returns>priority value with which this registration is read. Only the highest priority registration of each ID will be active</returns>
	public static int Blueprints_OverridePriority()
	{
		return 0;
	}
}
